#!/usr/bin/env bash

# Working with git repositories over the network on macOS an error could
# appear as follows: "fatal: Could not write new index file." If this happens
# regularly, run fixgit in the repository root. This bash script will backup the
# repository index file and copy in its place a new one which will solve the
# problem temporarily.

fixgit() {

    D=$(date +%Y%m%d%H%M%S)
    if test -f "./.git/index"; then
    	mv ./.git/index ./.git/index.bak$D
    	cp ./.git/index.bak$D ./.git/index
    	return 0
    else
    	echo "No Git repository found in current directory."
    	return 1
    fi

}
